title: Values
menu:
  img: null # string image path
  title: null # string
  sub: null # string
  items:
  - url: null # string; `langs` to relocate langs; `translate` to relocate translate
    icon: 1 # https://fontawesome.com/search?o=r&s=solid&f=brands%2Cclassic
    label: null # string
    anchor: null # string
    lock: y
    btn: none
    swap: n
    ga4: n
callnows:
- type: phone # [phone, whatsapp, mail]
  label: 123456789
  btn: cta # [ main, cta, alt, light, dark, turn, such, none ]
- type: whatsapp
  label: 123456789
  btn: whatsapp # [ main, cta, alt, light, dark, turn, such, none ]
- type: custom
  url: '#principal'
  icon: logout
  label: Personalizado
  anchor: Mola Mazo
  lock: n
  btn: light # [ main, cta, alt, light, dark, turn, such, none ]
  ga4: n
footer:
  color: dark
  div: squares
  md: |
    Example footer content